### ISSUE TITLE
Breaking change in evil brings `Symbol's value as a variable is void: evil-ex-cmd`

### ISSUE THREAD

**Issue by gagbo** [mamapanda/evil-traces#2]
Hello,

[This commit](https://github.com/emacs-evil/evil/commit/f84d3453b312bd8ec0a1c092d075bbc3d91e157b) in `evil-mode` changed something in the way ex commands are handled.

The main change that I see is that `evil-ex-cmd` has been removed, which ended up triggering this error:
- whenever I hit the `/` after a the start of a `:substitute` command I get this error
![](https://cdn.discordapp.com/attachments/897944277005520946/1133648351896797285/image.png)
- No preview of the change is displayed
- Trying to finish the command anyway ends up in an error "No Pattern is defined" or something, and no replacement occurs.

The only way to restore functionality of `:substitute` currently is to disable `evil-traces-mode`, which both removes previews and allows `:s/...` to work again.

**Comment by gagbo** [comment]
@hlissner spotted that the commit renamed `evil-ex-cmd` to `evil--ex-cmd`, so _maybe_ just applying `(defvaralias 'evil-ex-cmd evil--ex-cmd)` might work as a quick fix until there are changes in the repo here. But it's always a bit hard to understand the changes in evil

**Comment by mamapanda** [comment]
Hey, thanks for reporting this! I haven't updated my `evil` version for 2 years, so I never would've noticed :grin:

I think I fixed it (and a few other issues) in the latest version. Does it work for you now?

**Comment by gagbo** [comment]
Thanks for the response :) I have no issues at all with the current version
